# Generated by Django 2.0 on 2018-06-02 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('prix', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('phone1', models.CharField(max_length=10)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Categorie')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Commune')),
                ('specialite', models.ManyToManyField(to='account.Specialite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wilaya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Wilaya')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.AlterIndexTogether(
            name='job',
            index_together={('id', 'slug')},
        ),
    ]
