# Generated by Django 2.0 on 2018-06-10 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='category_image/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('proprietaire', 'Proprietaire'), ('enteprise', 'Enteprise')], default='proprietaire', max_length=12)),
                ('name', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=50)),
                ('overview', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('facebook_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('youtube_url', models.URLField()),
                ('site_web', models.URLField()),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('phone1', models.CharField(max_length=10)),
                ('total_like', models.PositiveIntegerField(db_index=True, default=0)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Categorie')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='specialite',
            field=models.ManyToManyField(to='account.Specialite'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='profiles_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='wilaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Wilaya'),
        ),
        migrations.AddField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Wilaya'),
        ),
    ]
